name: Deploy Angular App to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (using version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Build Angular project for production
      - name: Build Angular project
        run: npm run build -- --configuration=production

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --token "$FIREBASE_TOKEN"
