name: Deploy Angular to Firebase 🚀

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the latest stable version

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: ng build --configuration=production

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
