name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use Node.js version 18 or higher

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build -- --configuration=production

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase using FIREBASE_TOKEN
      run: |
        echo "$FIREBASE_TOKEN" > $HOME/firebase-service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"

    - name: Set Firebase project
      run: firebase use --project your-firebase-project-id --alias hosting

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --project your-firebase-project-id
